services:
  fastapi:
    build:
      context: .          
      dockerfile: Dockerfile
    image: aiops-fastapi:latest
    container_name: aiops
    ports:
      - "8001:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - DB_HOST=${DB_HOST}          
      - DB_PORT=${DB_PORT}          
      - DB_NAME=${DB_NAME}          
      - DB_USER=${DB_USER}          
      - DB_PASSWORD=${DB_PASSWORD} 
    restart: always
    volumes:
      - /home/user1/cloud-project-v2/aiops/sample.log:/app/sample.log     # 테스트용 볼륨