services:

  # -------------------------------------------------
  # Prometheus
  # 메트릭을 수집하는 모니터링 서버
  # -------------------------------------------------
  prometheus_settings:
    image: prom/prometheus:v3.12.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
    # 세팅값 들어가있는 yml 파일을 컨테이너 내부에 매핑
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    # alert 규칙이 들어가있는 yml 파일을 컨테이너 내부에 매핑
      - ./prometheus/alert_rules:/etc/prometheus/rules:ro
    # 수동으로 생성한 volume에 prometheus 컨테이너 정보를 저장
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=10GB' 
      - '--web.enable-lifecycle'

    networks:
      - monitoring
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION

  # -------------------------------------------------
  # AlertManager
  # Prometheus Alert 처리
  # -------------------------------------------------
  alert_manager_settings:
    image: prom/alertmanager:v0.32.1
    container_name: alert_manager
    restart: unless-stopped
    networks:
      - monitoring
    ports:
    - "9093:9093" 
    volumes:
    # alert manager 세팅 값 yml파일 넣기
      - ./alertmanager/alert_manager.yml:/etc/alertmanager/alertmanager.yml:ro
    # alert manager 로그 기록 넘길 volume 마운트
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--cluster.listen-address='

  # -------------------------------------------------
  # Grafana
  # 모니터링 대시보드
  # -------------------------------------------------
  grafana_settings:
    image: grafana/grafana:11.6.15
    container_name: grafana
    restart: unless-stopped
    networks:
      - monitoring
    ports:
    - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin           
      - GF_SECURITY_ADMIN_PASSWD=admin 
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel 
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/grafana_dashboard.json

  # -----------------------------
  # grafana, cicd fastapi
  # -----------------------------
  fastapi:
    build: ./mgmt_settings/fastapi
    container_name: fastapi
    ports:
      - "8001:8001"
    volumes:
      - ./fastapi/src:/app
    env_file:                             
      - ./fastapi/.env   
    restart: unless-stopped

  # -------------------------------------------------
  # Management Runner
  # Terraform / Ansible 실행 환경
  # -------------------------------------------------
  mgmt-runner:

    build:
      context: ./management/runner

    container_name: mgmt-runner

    tty: true
    stdin_open: true

    volumes:

      # Terraform 코드
      - ./terraform:/workspace/terraform

      # Ansible 코드
      - ./ansible:/workspace/ansible

      # 배포 대상 코드
      - ./web:/workspace/web

    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION

    restart: unless-stopped

    networks:
      - project2-network

# -------------------------------------------------
# Docker Named Volume
# -------------------------------------------------
volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:

# -------------------------------------------------
# Docker Network
# -------------------------------------------------
networks:

  # Prometheus
  # Grafana
  # AlertManager
  # FastAPI
  # mgmt-runner
  #
  # 컨테이너 간 통신용 네트워크
  project2-network:
    driver: bridge