# -------------------------------------------------
# Prometheus Global Settings
# -------------------------------------------------

global:

  # 메트릭 수집 주기
  scrape_interval: 15s

# -------------------------------------------------
# 수집 대상
# -------------------------------------------------

scrape_configs:

  # Prometheus 자기 자신 모니터링
  - job_name: prometheus

    static_configs:
      - targets:
          - prometheus:9090

  # 현재는 테스트 코드 (컨테이너들이 잘 연동되는지만 테스트하기 위함)
  # 추후에 EC2상의 인스턴스들 ip를 연결해야함
  
  # Terraform
  # ↓
  # EC2 생성
  # ↓
  # Prometheus 자동 등록