# -------------------------------------------------
# Prometheus Global Settings
# -------------------------------------------------

global:

  # 메트릭 수집 주기
  scrape_interval: 15s

# ----------------------------
# alertmanagers에게 신호 보내기
# ----------------------------
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alert_manager:9093'
            
# 어떤 규칙으로 보낼지 정의된 파일 읽게하기
rule_files:
  - /etc/prometheus/rules/*.yml
# -------------------------------------------------
# 수집 대상
# -------------------------------------------------

scrape_configs:

  # Prometheus 자기 자신 모니터링
  - job_name: prometheus

    static_configs:
      - targets:
          - prometheus:9090

  - job_name: 'aws-was-nodes'
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 9100
    relabel_configs:
      # 인스턴스 상태가 running 인 것만 수집
      - source_labels: [__meta_ec2_instance_state]
        regex: running
        action: keep
      # 태그 Role = WAS 인 인스턴스만 수집
      - source_labels: [__meta_ec2_tag_Role]
        regex: WAS
        action: keep
      # 수집 타겟 IP를 프라이빗 IP로 변경
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
        replacement: "${1}:9100"
      
      # EC2의 네임 태그 확인
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name