--- # galaxy 이용버전
- name: "Prometheus설치 및 설정(connection활용)"
  include_role:
    name: prometheus.prometheus.prometheus

  vars:
    # 1. 글로벌 설정
    prometheus_global:
      scrape_interval: 15s

    # 2. 타겟 수집 설정
    prometheus_scrape_configs:
      # 1. 프로메테우스 애플리케이션 자체의 상태
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # 2. 바스천 서버의 OS 상태 (CPU, 메모리 등)
      - job_name: 'bastion_node'
        static_configs:
          - targets: ['localhost:9100']

      # 3. WAS 서버 자동 탐지 
      - job_name: 'was_servers'
        ec2_sd_configs:
          - region: ap-northeast-2
            port: 9100
        relabel_configs:
          - source_labels: [__meta_ec2_tag_Role]
            regex: WAS
            action: keep
          - source_labels: [__meta_ec2_tag_Name]
            target_label: instance

      # 4. DB 서버(Node) 자동 탐지 (Node Exporter)
      - job_name: 'db_servers'
        ec2_sd_configs:
          - region: ap-northeast-2
            port: 9100
        relabel_configs:
          - source_labels: [__meta_ec2_tag_Role]
            regex: DB  
            action: keep
          - source_labels: [__meta_ec2_tag_Name]
            target_label: instance

      # 5. DB 서버의 데이터베이스 상태 수집 (Postgres Exporter)
      - job_name: 'db_postgres'
        ec2_sd_configs:
          - region: ap-northeast-2
            port: 9187  
        relabel_configs:
          - source_labels: [__meta_ec2_tag_Role]
            regex: DB
            action: keep
          - source_labels: [__meta_ec2_tag_Name]
            target_label: instance