---
- name: "Grafana YUM 저장소 등록"
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/grafana.repo
    content: |
      [grafana]
      name=grafana
      baseurl=https://rpm.grafana.com
      enabled=1
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=https://rpm.grafana.com/gpg.key
      sslverify=1
      sslcacert=/etc/pki/tls/certs/ca-bundle.crt

- name: "Grafana 설치"
  ansible.builtin.dnf:
    name: grafana
    state: present
    update_cache: no


- name: Enable grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started