---
  - name: 현재 EC2 인스턴스의 토큰 가져오기 (IMDSv2)
    uri:
      url: http://169.254.169.254/latest/api/token
      method: PUT
      headers:
        X-aws-ec2-metadata-token-ttl-seconds: "21600"
      return_content: yes
    register: ec2_token

  - name: 현재 EC2 인스턴스 ID 가져오기
    uri:
      url: http://169.254.169.254/latest/meta-data/instance-id
      headers:
        X-aws-ec2-metadata-token: "{{ ec2_token.content }}"
      return_content: yes
    register: ec2_metadata

  - name: AMI 캡처
    amazon.aws.ec2_ami:
      instance_id: "{{ ec2_metadata.content }}"
      name: "project01-was-ami-{{ ansible_date_time.iso8601_basic_short }}"
      wait: yes
    delegate_to: localhost
    become: false
    register: captured_ami

  - name: 생성된 AMI ID 출력
    debug:
      msg: "AMI 생성 완료 → {{ captured_ami.image_id }}"
    delegate_to: localhost
    become: false