name: "DB Image Build & Push"

on:
  push:
    branches: ["main"]
    paths:
      - "docker/eventdb.sql"
      - "docker/Dockerfile.db"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: AWS ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        # self-hosted runner에 설정된 AWS 자격 증명을 그대로 사용합니다.

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v3

      - name: DB 이미지 빌드 & Push
        uses: docker/build-push-action@v5
        with:
          context: docker
          file: docker/Dockerfile.db
          push: true
          tags: |
            644724502235.dkr.ecr.ap-northeast-2.amazonaws.com/project02-db-repo:latest
            644724502235.dkr.ecr.ap-northeast-2.amazonaws.com/project02-db-repo:${{ github.sha }}
