name: "DB Image Build & Push"

on:
  push:
    branches: ["main"]
    paths:
      - "docker/eventdb.sql"
      - "docker/Dockerfile.db"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v3

      - name: DB 이미지 빌드 & Push
        uses: docker/build-push-action@v5
        with:
          context: docker
          file: docker/Dockerfile.db
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/project02-db:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/project02-db:${{ github.sha }}
