name: "Infra Destroy"

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform/envs/dev
        run: terraform destroy -auto-approve