name: "Scaling"

on:
  workflow_dispatch:
    inputs:
      desired_capacity:
        description: "Target capacity size for the Auto Scaling Group (Scale-In/Out)"
        required: true
        default: "3"

concurrency:
  group: terraform-state
  cancel-in-progress: false

jobs:
  scale:
    runs-on: self-hosted
    
    env:
      TF_VAR_tailscale_auth_key: ${{ secrets.TAILSCALE_AUTH_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform Environment
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Apply Scaling Changes
        working-directory: terraform/envs/dev
        run: |
          terraform apply \
            -auto-approve \
            -var="desired_capacity=${{ github.event.inputs.desired_capacity }}"