name: "Terraform Infrastructure Apply"

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: self-hosted # mgmt-runner 내부에서 실행

    env:
      TF_VAR_tailscale_auth_key: ${{ secrets.TAILSCALE_AUTH_KEY }}
      TF_VAR_db_user:            ${{ secrets.DB_USER }}
      TF_VAR_db_password:        ${{ secrets.DB_PASSWORD }}

    defaults:
      run:
        working-directory: ./terraform/envs/dev

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Cleanup Terraform Cache
        if: always()
        run: rm -rf .terraform .terraform.lock.hcl tfplan