name: "Terraform Infrastructure Provisioning"

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted # mgmt-runner 내부에서 실행

    # mgmt-runner 컨테이너에는 docker-compose를 통해
    # AWS_ACCESS_KEY_ID 등이 이미 주입되어 있으므로
    # 별도의 Configure AWS Credentials 스텝이 필요 없습니다!

    defaults:
      run:
        working-directory: ./terraform/envs/dev

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
